// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🌐 WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJtWk7jMhfXFWy6KdaHqjAAAdEDI36AE',
    appId: '1:629223467984:web:b8b6878c44167ac4c8a7d5',
    messagingSenderId: '629223467984',
    projectId: 'bloomory-37b33',
    authDomain: 'bloomory-37b33.firebaseapp.com',
    storageBucket: 'bloomory-37b33.firebasestorage.app',
    measurementId: 'G-14TNKEG48M',
  );

  /// 🤖 ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0fAUk4x8NT5v9D7jGyKm3z9S1bjOWRxs',
    appId: '1:629223467984:android:d861ad6e10292229c8a7d5',
    messagingSenderId: '629223467984',
    projectId: 'bloomory-37b33',
    storageBucket: 'bloomory-37b33.firebasestorage.app',
  );

  /// 🍎 IOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASFfX6OdbDsPStM7AfcfWTmXvWKlLCYts',
    appId: '1:629223467984:ios:c728ac661fbec72cc8a7d5',
    messagingSenderId: '629223467984',
    projectId: 'bloomory-37b33',
    storageBucket: 'bloomory-37b33.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
    iosClientId:
        '629223467984-0mt8js3r51ooj2pftfccte79o8r3og5f.apps.googleusercontent.com',
  );
}
