import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'routes/app_routes.dart';
import 'core/services/app_appearance_controller.dart';
import 'core/theme/app_theme.dart';
import 'services/local_photo_store.dart';

// ✅ this file must exist (generated by flutterfire configure)
import 'firebase_options.dart';

Future<void> main() async {
  // ignore: avoid_print
  print('APP START');
  WidgetsFlutterBinding.ensureInitialized();
  debugPrint('[Bloomory] app start');

  await runZonedGuarded(() async {
    await _initializeAndRunApp();
  }, (Object error, StackTrace stack) {
    debugPrint('[CRASH] runZonedGuarded uncaught: $error');
    debugPrintStack(label: '[CRASH] zone stack', stackTrace: stack);
  });
}

Future<void> _initializeAndRunApp() async {
  FlutterError.onError = (FlutterErrorDetails details) {
    debugPrint('[CRASH] FlutterError.onError');
    debugPrint('[CRASH] exception: ${details.exceptionAsString()}');
    if (details.stack != null) {
      debugPrintStack(
        label: '[CRASH] FlutterError stack',
        stackTrace: details.stack,
      );
    }
    FlutterError.dumpErrorToConsole(details);
  };

  ui.PlatformDispatcher.instance.onError = (Object error, StackTrace stack) {
    debugPrint('[CRASH] PlatformDispatcher.onError');
    debugPrint('[CRASH] exception: $error');
    debugPrintStack(
      label: '[CRASH] PlatformDispatcher stack',
      stackTrace: stack,
    );
    return true;
  };

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint('[Bloomory] Firebase init OK');
  } catch (e, st) {
    debugPrint('[Bloomory] Firebase init FAILED (some features disabled): $e\n$st');
  }

  try {
    await LocalPhotoStore.init();
    debugPrint('[Bloomory] DB init success (LocalPhotoStore)');
  } catch (e, st) {
    debugPrint(
      '[Bloomory] LocalPhotoStore init FAILED (local timeline albums disabled): $e\n$st',
    );
  }

  try {
    await AppAppearanceController.instance.load();
  } catch (e, st) {
    debugPrint('[Bloomory] Appearance init FAILED: $e\n$st');
  }

  // ignore: avoid_print
  print('BEFORE runApp');
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    // ignore: avoid_print
    print('HOME INIT START');
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: AppAppearanceController.instance,
      builder: (context, _) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: AppAppearanceController.instance.themeMode,
          initialRoute: AppRoutes.splash,
          routes: AppRoutes.routes,
        );
      },
    );
  }
}
