import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'routes/app_routes.dart';
import 'core/theme/app_theme.dart';

// ✅ this file must exist (generated by flutterfire configure)
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,

      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.light,

      initialRoute: AppRoutes.splash,
      routes: AppRoutes.routes,
    );
  }
}
