import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:app_links/app_links.dart';

import 'routes/app_routes.dart';
import 'core/services/album_api_service.dart';
import 'core/services/app_appearance_controller.dart';
import 'core/theme/app_theme.dart';
import 'features/chat/album_chat_screen.dart';
import 'features/timeline/album_detail_screen.dart';
import 'services/local_photo_store.dart';

// ✅ this file must exist (generated by flutterfire configure)
import 'firebase_options.dart';

Future<void> main() async {
  // ignore: avoid_print
  print('APP START');
  WidgetsFlutterBinding.ensureInitialized();
  debugPrint('[Bloomory] app start');

  await runZonedGuarded(() async {
    await _initializeAndRunApp();
  }, (Object error, StackTrace stack) {
    debugPrint('[CRASH] runZonedGuarded uncaught: $error');
    debugPrintStack(label: '[CRASH] zone stack', stackTrace: stack);
  });
}

Future<void> _initializeAndRunApp() async {
  FlutterError.onError = (FlutterErrorDetails details) {
    debugPrint('[CRASH] FlutterError.onError');
    debugPrint('[CRASH] exception: ${details.exceptionAsString()}');
    if (details.stack != null) {
      debugPrintStack(
        label: '[CRASH] FlutterError stack',
        stackTrace: details.stack,
      );
    }
    FlutterError.dumpErrorToConsole(details);
  };

  ui.PlatformDispatcher.instance.onError = (Object error, StackTrace stack) {
    debugPrint('[CRASH] PlatformDispatcher.onError');
    debugPrint('[CRASH] exception: $error');
    debugPrintStack(
      label: '[CRASH] PlatformDispatcher stack',
      stackTrace: stack,
    );
    return true;
  };

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint('[Bloomory] Firebase init OK');
  } catch (e, st) {
    debugPrint('[Bloomory] Firebase init FAILED (some features disabled): $e\n$st');
  }

  try {
    await LocalPhotoStore.init();
    debugPrint('[Bloomory] DB init success (LocalPhotoStore)');
  } catch (e, st) {
    debugPrint(
      '[Bloomory] LocalPhotoStore init FAILED (local timeline albums disabled): $e\n$st',
    );
  }

  try {
    await AppAppearanceController.instance.load();
  } catch (e, st) {
    debugPrint('[Bloomory] Appearance init FAILED: $e\n$st');
  }

  // ignore: avoid_print
  print('BEFORE runApp');
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static const List<String> _trustedHosts = <String>[
    'bloomoryai.com',
    'www.bloomoryai.com',
  ];
  static final RegExp _inviteCodePattern = RegExp(r'^[a-zA-Z0-9_-]{6,}$');
  final GlobalKey<NavigatorState> _navKey = GlobalKey<NavigatorState>();
  final GlobalKey<ScaffoldMessengerState> _messengerKey =
      GlobalKey<ScaffoldMessengerState>();
  StreamSubscription<Uri?>? _linkSub;
  final AppLinks _appLinks = AppLinks();
  bool _handledInitialLink = false;

  @override
  void initState() {
    super.initState();
    // ignore: avoid_print
    print('HOME INIT START');
    _initDeepLinks();
  }

  @override
  void dispose() {
    _linkSub?.cancel();
    super.dispose();
  }

  Future<void> _initDeepLinks() async {
    try {
      final initial = await _appLinks.getInitialLink();
      if (!_handledInitialLink && initial != null) {
        _handledInitialLink = true;
        await _handleIncomingUri(initial);
      }
    } catch (_) {}

    _linkSub = _appLinks.uriLinkStream.listen(
      (uri) => unawaited(_handleIncomingUri(uri)),
      onError: (_) {},
    );
  }

  Future<void> _handleIncomingUri(Uri uri) async {
    final inviteCode = _extractInviteCode(uri);
    if (inviteCode == null || inviteCode.isEmpty) return;
    if (!_inviteCodePattern.hasMatch(inviteCode)) {
      debugPrint('[DeepLink] invalid invite code format: $inviteCode');
      return;
    }
    debugPrint('[DeepLink] accepted invite: $inviteCode');

    try {
      final albumId = await AlbumApiService.joinAlbumByInviteCode(inviteCode);
      final nav = _navKey.currentState;
      if (nav == null || !mounted) return;

      nav.push(
        MaterialPageRoute<void>(
          builder: (_) => TimelineAlbumDetailScreen(
            albumId: albumId,
            albumTitle: 'Shared Memory',
          ),
        ),
      );

      _messengerKey.currentState?.showSnackBar(
        const SnackBar(content: Text('You joined this memory 🎉')),
      );

      Future<void>.delayed(const Duration(milliseconds: 300), () {
        final nav2 = _navKey.currentState;
        if (nav2 == null || !mounted) return;
        nav2.push(
          MaterialPageRoute<void>(
            builder: (_) => AlbumChatScreen(
              albumId: albumId,
              albumTitle: 'Shared Memory',
            ),
          ),
        );
      });
    } catch (_) {
      _messengerKey.currentState?.showSnackBar(
        const SnackBar(content: Text('Invalid or expired invite')),
      );
    }
  }

  String? _extractInviteCode(Uri uri) {
    final seg = uri.pathSegments;
    if (uri.scheme == 'bloomory') {
      if (uri.host == 'album' && seg.length >= 2 && seg[0] == 'invite') {
        return seg[1];
      }
      if (seg.length >= 2 && seg[0] == 'invite') {
        return seg[1];
      }
    }
    if (uri.scheme == 'https') {
      if (!_trustedHosts.contains(uri.host)) {
        debugPrint('[DeepLink] rejected host: ${uri.host} uri=$uri');
        return null;
      }
      if (seg.length < 2 || seg[0] != 'invite') {
        return null;
      }
      return seg[1];
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: AppAppearanceController.instance,
      builder: (context, _) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          navigatorKey: _navKey,
          scaffoldMessengerKey: _messengerKey,
          theme: AppTheme.lightTheme,
          darkTheme: AppTheme.darkTheme,
          themeMode: AppAppearanceController.instance.themeMode,
          initialRoute: AppRoutes.splash,
          routes: AppRoutes.routes,
        );
      },
    );
  }
}
